spring:
  rabbitmq:
    host: localhost
    port: 6565
    password: guest
    username: guest
grpc:
  client:
    edu-cost-stat-query-service:
      address: static://localhost:7575
      negotiationType: plaintext
server:
  port : 8080