spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
grpc:
  client:
    edu-cost-stat-query-service:
      address: static://localhost:6565
      negotiationType: plaintext
server:
  port : 8082